workflows:
  react-native-ios:
    name: React Native iOS Build

    environment:
      vars:
        NODE_VERSION: 18

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Archive
        script: |
          xcodebuild \
            -workspace ios/CoinMob.xcworkspace \
            -scheme CoinMob \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/ios/archive.xcarchive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=4AGSB844ZR \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/ios/archive.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ios/ipa \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa
